spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/start_jpa
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true

  data:
    web:
      pageable:
        default-page-size: 10