spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/start_jpa
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true

  data:
    web:
      pageable:
        default-page-size: 10

  mail:
    host: smtp.gmail.com
    port: 587
    username: pickleradish0222@gmail.com
    password: pickletest
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG